// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCoffeeStore.Data;

#nullable disable

namespace OnlineCoffeeStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250428082128_AddCategoryIdToCoffee")]
    partial class AddCategoryIdToCoffee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineCoffeeStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Espresso"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Latte"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Mocha"
                        });
                });

            modelBuilder.Entity("OnlineCoffeeStore.Models.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Coffees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Ingredients = "Espresso",
                            Name = "Espresso Shot",
                            Price = 2.0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Ingredients = "Espresso, Milk, Ice",
                            Name = "Iced Latte",
                            Price = 3.5,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Ingredients = "Espresso, Milk, Chocolate Syrup, Ice",
                            Name = "Mocha Frappe",
                            Price = 4.0,
                            Status = 1
                        });
                });

            modelBuilder.Entity("OnlineCoffeeStore.Models.Coffee", b =>
                {
                    b.HasOne("OnlineCoffeeStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
